apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "db"  }}
    chart: "{{ template "wordpress.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
